Translate: [editing.md] - [adding/editing]
mizerablebr/anki-manual pull request #7
Opened 2020-09-19 14:24 UTC by Cardosaum

A tradução está feita. 

Se desejarem, comentem o que acharam da tradução. 

Por favor, se tem alguma coisa que gostariam de mudar, qualquer detalhe que seja, podem avisar que eu modifico o texto.

2020-09-19 14:51 UTC, DyeffersonAz requested changes
Sugiro, portanto, que o uso de "deck" deva ser discutido, pois a palavra "baralho" é usada na interface. Além disso, a questão das reticências.

2020-09-19 14:51 UTC, DyeffersonAz commented on editing.md
> +_então a nota que você adicionar terá duas etiquetas.
Só uma dúvida: por que optou pela "underscore" aqui sendo que as reticências do original são ideia de continuação ao parágrafo anterior? Ainda não havia visto esse tipo de uso pro "_".

2020-09-19 14:51 UTC, DyeffersonAz commented on editing.md
> +e colocado no deck que você selecionou. Se você quiser editar um cartão já
Outra discussão: o uso em português deve ser "baralho" ou "deck"?

2020-09-19 14:59 UTC, Cardosaum commented
> Sugiro, portanto, que o uso de "deck" deva ser discutido, pois a palavra "baralho" é usada na interface. Além disso, a questão das reticências.

Muito obrigado pelo olhar atento. eu inseri "deck" acidentalmente. o correto é mesmo "baralho".

2020-09-19 15:03 UTC, Cardosaum commented on editing.md
> +_então a nota que você adicionar terá duas etiquetas.
Obrigado por comentar esse detalhe. no meu editor de texto a formatação de `…` e `_` é praticamente igual. (eu havia achado estranho eles colorarem `_` como continuação de texto, mas, uma vez que na minha percepção o caractere contido na versão original era `_`, achei por bem mantê-lo).

Mudarei a fonte do meu editor. haha

2020-09-19 15:04 UTC, Cardosaum commented on editing.md
> +e colocado no deck que você selecionou. Se você quiser editar um cartão já
Deve ser "baralho". foi erro meu ter digitado a versão em inglês nesse trecho. Muito obrigado pela atenção aos detalhes!

2020-09-19 15:05 UTC, DyeffersonAz commented on editing.md
> +_então a nota que você adicionar terá duas etiquetas.
@Cardosaum Bem, então você pode dar um resolve nas que você corrigir no texto.

2020-09-19 19:11 UTC, Cardosaum commented
@DyeffersonAz 

Mudanças realizadas. Mais uma vez, obrigado pela atenção na revisão

2020-09-19 19:25 UTC, DyeffersonAz approved these changes
Agora ao meu ver está ótimo.

2020-09-21 17:59 UTC, mizerablebr commented on editing.md
> +cartões serão adicionados. Se você quiser adicionar cartões à um novo baralho,
Suspeito que não seja o caso de uso de crase antes de artigo indefinido "um", não seria melhor "adicionar cartões a um novo baralho"

2020-09-21 18:00 UTC, mizerablebr commented on editing.md
> +Em baixo do tipo de nota, você verá alguns botões e uma área chamada "Frente" e
A locução adverbial seria "Embaixo", escrito junto, confere?

2020-09-21 18:18 UTC, mizerablebr commented on editing.md
> +para adicionar essa nota à sua coleção. Após isso, um cartão também será criado,
Apesar do uso das vírgulas no original, suspeito não ser o caso de uma oração adverbial. Motivo pelo qual discordo da segunda vírgula, pois estaria separando o sujeito do predicado. Minha sugestão é por "Após isso, um cartão também **será criado e colocado** no baralho que você selecionou."

2020-09-21 18:20 UTC, mizerablebr commented on editing.md
> +te avisar caso você adicione dois cartões com o campo Frente contendo o texto
Assim como em outros lugares, sugiro ocultar o pronome "te".

2020-09-21 18:34 UTC, Cardosaum commented
Grato pelas correções, @mizerablebr 
Todas pertinentes!

2020-09-23 14:06 UTC, merged